name: Update helm chart dependencies

on:
  repository_dispatch:
    types: [helm-update-deps]

jobs:
  release:
    uses: onecx/ci-common/.github/workflows/helm-update-deps.yml@v1
    secrets: inherit
