name: Build helm chart

on:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
    paths:
      - 'helm/**'      

jobs:
  release:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    with:
      push: true
      artifact: ''    
      helmdir: 'helm'
      helmAbsoluteDir: true    
